### ISSUE TITLE
Issue with GrainStorageContext since Orleans 3.0.0-rc1

### ISSUE THREAD

**Issue by KSLcom** [OrleansContrib/Orleans.Providers.EntityFramework#16]
Something wrong with GrainStorageContext since Orleans 3.0.0-rc1 release. GrainStorageContext<TGrainState>.IsConfigured in GrainStorage.WriteStateAsync always return false.
It seems the problem releated to AsyncLocal values in GrainStorageContext.

With Orleans 3.0.0-beta1 all seems OK.

**Comment by alirezajm** [comment]
@KSLcom I didn't have a chance to check it out yet. Will do in a few days.

**Comment by alirezajm** [comment]
@KSLcom I ran tests against 3.0.0-rc1 didn't see a problem. Can you share a repro?

In the meantime you can use 'IGrainStateEntryConfigurator<TContext, TGrain, TEntity>', I updated the readme file you can find a bit more info there.

**Comment by KSLcom** [comment]
Sorry for delay to answer. In my simple test case with rc1 the problem is not reproduced also. But in the real project GrainStorageContext.IsConfigured always return false when swithing to Orleans 3.0.0-rc1. After rollback to Orleans 3.0.0-beta1 is working again as expected. Will investigate on my side.
