### ISSUE TITLE
Dead Project - Take Over

### ISSUE THREAD

**Issue by SilentBlueD666** [OrleansContrib/Orleans.Providers.EntityFramework#24]
As it appears the original contributors are no longer maintaining the project how do we go about taking over?

While EF Core would not be first choice as a storage provider there are still some use cases where can be beneficial.

**Comment by alirezajm** [comment]
Been a while that I wanted to upgrade this. Now, there seems to be a need and I have some time to do this. You can track it here https://github.com/OrleansContrib/Orleans.Providers.EntityFramework/issues/25

**Comment by SilentBlueD666** [comment]
I had a go at the weekend, I did a fork, quite a few breaking changes that I just hammered around. But willing to drop my fork I spent most of the time trying to figure out why it was doing what it was, and pretty cool really 😁

Main problem that I wasn't able to get around is you no longer get the grain type from Orleans, it's been replaced with the 'StateName'

**Comment by alirezajm** [comment]
I'm afraid there will be more breaking changes, since last supported version was 3!

**Comment by SilentBlueD666** [comment]
Yep 😁 

OK, so I pushed up all the changings I made to my fork, but with the view to delete, but thought maybe good for you to see first, you can find here: [SilentBlueD666/Orleans.Persistence.EntityFramework](https://github.com/SilentBlueD666/Orleans.Persistence.EntityFramework), I will close this issue.
